# Options that select which devices and features PlusLib is built with.
#
# The superbuild seeds these in the cache before PlusLib is configured, so what
# it passes still decides the build. Declaring them here means that PlusLib on
# its own is configurable too: previously these were only ever read, never
# declared, so a standalone configure silently produced a build with every
# device disabled and no way to see or change that in the CMake GUI.

option(PLUS_ENABLE_VIDEOSTREAMING "Provide support for streaming compressed video from Plus" OFF)
option(PLUS_TEST_BKPROFOCUS "Enable testing of acquisition from BK ProFocus ultrasound systems. Enable this only if a BK ProFocus device is connected to this computer. " OFF)
option(PLUS_TEST_HIGH_ACCURACY_TIMING "Enable testing of high-accuracy timing. High-accuracy timing may not be available on virtual machines and so testing may be turned off to avoid false alarams." ON)
option(PLUS_TEST_LEAPMOTION "Enable testing of LeapMotion device" OFF)
option(PLUS_TEST_MMF_VIDEO "Enable testing of acquisition from MMF video device (webcam). Enable this only if an MMF device is connected to this computer." OFF)
option(PLUS_TEST_OvrvisionPro "Enable testing of acquisition of stereo images from the OvrvisionPro" OFF)
option(PLUS_TEST_PHILIPS_3D_ULTRASOUND "Enable testing of acquisition from Philips 3D ultrasound systems. Enable this only if a Philips device is accessible from this computer. " OFF)
option(PLUS_TEST_TELEMED "Enable testing of acquisition from Telemed ultrasound systems. Enable this only if a Telemed device is connected to this computer. " OFF)
option(PLUS_TEST_ULTRASONIX "Enable testing of acquisition from Ultrasonix ultrasound systems. Enable this only if an Ultrasonix device accessible from this computer. " OFF)
option(PLUS_USE_3dConnexion_TRACKER "Provide support for the 3dConnexion 3d mouse" OFF)
option(PLUS_USE_AGILENT "Provide support for the Agilent digitizer device" OFF)
option(PLUS_USE_ANDOR_CAMERA "Provide support for the Andor cameras capture stream" OFF)
option(PLUS_USE_ATRACSYS "Provide support for Atracsys optical trackers" OFF)
option(PLUS_USE_AZUREKINECT "Provide support for Azure Kinect cameras" OFF)
option(PLUS_USE_Ascension3DG "Provide support for the Ascension 3DG Tracker" OFF)
option(PLUS_USE_Ascension3DGm "Provide support for the Ascension MedSafe Tracker" OFF)
option(PLUS_USE_BKPROFOCUS_CAMERALINK "Enable acquisition from BK ProFocus ultrasound systems through CameraLink interface" OFF)
option(PLUS_USE_BKPROFOCUS_VIDEO "Provide support for BK ProFocus ultrasound systems through the OEM (TCP/IP) interface" OFF)
option(PLUS_USE_BLACKMAGIC_DECKLINK "Provide support for BlackMagic DeckLink capture cards." OFF)
option(PLUS_USE_BRACHY_TRACKER "Provide support for the Brachy Steppers" OFF)
option(PLUS_USE_CAPISTRANO_VIDEO "Provide support for the Capistrano Labs USB ultrasound probes" OFF)
option(PLUS_USE_CLARIUS "Provide support for Clarius Ultrasound devices via the Listen API" OFF)
option(PLUS_USE_CLARIUS_OEM "Provide support for Clarius OEM SDK interface to Clarius Ultrasound devices." OFF)
option(PLUS_USE_DAQVIDEOSOURCE "Provide support for capturing an CameraLink Camera using DAQ System USB3-FRM13-B Grabber" OFF)
option(PLUS_USE_EPIPHAN "Provide support for the Epiphan framegrabber device" OFF)
option(PLUS_USE_GENERIC_SENSOR_TRACKER "Provide support for generic sensor data collection" OFF)
option(PLUS_USE_ICCAPTURING_VIDEO "Provide support for the IC framegrabber device" OFF)
option(PLUS_USE_INFRARED_SEEK_CAM "Provide support for capturing an Infrared Seek Camera capture stream" OFF)
option(PLUS_USE_INFRARED_TEEV2_CAM "Provide support for capturing an Infrared Therma Expert EV2 Camera capture stream" OFF)
option(PLUS_USE_INFRARED_TEQ1_CAM "Provide support for capturing an Infrared Therma Expert Q1 Camera capture stream" OFF)
option(PLUS_USE_INTELREALSENSE "Provide support for Intel RealSense cameras" OFF)
option(PLUS_USE_INTERSONARRAYSDKCXX_VIDEO "Provide support for the Interson Array SDK with C++ Wrapper USB ultrasound probes" OFF)
option(PLUS_USE_INTERSONSDKCXX_VIDEO "Provide support for the Interson SDK 1.X with C++ Wrapper USB ultrasound probes" OFF)
option(PLUS_USE_INTERSON_VIDEO "Provide support for the Interson USB ultrasound probes" OFF)
option(PLUS_USE_IntuitiveDaVinci "Provide support for the da Vinci Surgical System" OFF)
option(PLUS_USE_LEAPMOTION "Provide support for the LeapMotion hand tracker" OFF)
option(PLUS_USE_MICRONTRACKER "Provide support for the Claron MicronTracker" OFF)
option(PLUS_USE_MKV_IO "Enable reading/writing MKV files using libwebm." OFF)
option(PLUS_USE_MMF_VIDEO "Provide support for the Microsoft Media Foundation video digitizers (requires installation of Windows Platform SDK 7.1 or later)" OFF)
option(PLUS_USE_NDI "Provide support for the NDI POLARIS and AURORA" OFF)
option(PLUS_USE_NDI_CERTUS "Provide support for the NDI Certus" OFF)
option(PLUS_USE_NVIDIA_DVP "Provide support for the NVidia Digital Video Pipeline" OFF)
option(PLUS_USE_OPENHAPTICS "Provide support of OpenHaptics devices" OFF)
option(PLUS_USE_OPTICAL_MARKER_TRACKER "Provide support of tracking of markers (2D barcodes) in image streams using ArUco and OpenCV." OFF)
option(PLUS_USE_OPTIMET_CONOPROBE "Provide support for the Optimet ConoProbe" OFF)
option(PLUS_USE_OPTITRACK "Provide support for the OptiTrack tracking system" OFF)
option(PLUS_USE_OpenCV_VIDEO "Provide support for capturing an OpenCV capture stream" OFF)
option(PLUS_USE_OvrvisionPro "Provide support for the OvrvisionPro Stereo Camera" OFF)
option(PLUS_USE_PHIDGET_SPATIAL_TRACKER "Provide support for the Phidget Spatial accelerometer" OFF)
option(PLUS_USE_PHILIPS_3D_ULTRASOUND "Provide support for the Philips ie33 3D ultrasound probe" OFF)
option(PLUS_USE_PICOSCOPE "Provide support for PicoScope 2xxx series oscilloscopes" OFF)
option(PLUS_USE_REVOPOINT3DCAMERA "Provide support for Revopoint 3D cameras" OFF)
option(PLUS_USE_SPINNAKER_VIDEO "Provide support for Point Grey Spinnaker API compatible imaging devices" OFF)
option(PLUS_USE_STEALTHLINK "Provide support for the Medtronick StealthLink Server" OFF)
option(PLUS_USE_STEAMVR "Provide support for SteamVR tracking system" OFF)
option(PLUS_USE_TELEMED_VIDEO "Provide support for the Telemed ultrasound probes" OFF)
option(PLUS_USE_THORLABS_VIDEO "Provide support for the ThorLabs Compact Spectrometers" OFF)
option(PLUS_USE_TextRecognizer "Enable the text recognizer virtual device" OFF)
option(PLUS_USE_ULTRASONIX_VIDEO "Provide support for the Ultrasonix ultrasound systems" OFF)
option(PLUS_USE_ULTRAVIOLET_PCOUV_CAM "Provide support for capturing an PCO Ultraviolet Camera capture stream" OFF)
option(PLUS_USE_USDIGITALENCODERS_TRACKER "Provide support for multiple USDigital encoders tracking device" OFF)
option(PLUS_USE_V4L2 "Provide support for video4linux devices" OFF)
option(PLUS_USE_VP9 "Compile OpenIGTLink with VP9 support for compressed video streaming" OFF)
option(PLUS_USE_WINPROBE_VIDEO "Provide support WinProbe ultrasound systems" OFF)
option(PLUS_USE_WITMOTIONTRACKER "Provide support for the WitMotion IMU Trackers" OFF)

# Set by the superbuild, which names some of these differently.
option(PLUS_USE_SLICER "Get VTK, ITK and OpenIGTLink from a 3D Slicer build tree" OFF)
option(PLUS_USE_OpenIGTLink "Provide support for OpenIGTLink communication" OFF)
option(PLUS_USE_OpenCV "Use OpenCV for optical marker tracking and other features" OFF)
option(PLUS_USE_aruco "Use aruco for optical marker tracking" OFF)
option(PLUS_BUILD_WIDGETS "Build the PlusLib Qt widgets" OFF)
option(PLUSBUILD_BUILD_PlusLib_TOOLS "Build the PlusLib tools (PlusServer, PlusServerRemoteControl...)" ON)
option(PLUS_OFFLINE_BUILD "Build without an internet connection, and without querying the repository" OFF)

# Read by PlusLib alone.
option(PLUS_USE_SIMPLE_TIMER "Use simple timer instead of accurate timer" OFF)
option(PLUS_USE_INTEL_MKL "Use Intel Math Kernel Library for spectral analysis" OFF)
option(PLUS_USE_SYSTEM_ZLIB "Use the system zlib rather than the one bundled with VTK" OFF)
mark_as_advanced(PLUS_USE_SIMPLE_TIMER PLUS_TEST_HIGH_ACCURACY_TIMING PLUS_USE_SYSTEM_ZLIB)
