name: Continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Specify VTK version
  VTK_HASH: 6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # v9.4.1
  # Specify ITK version
  ITK_HASH: 898def645183e6a2d3293058ade451ec416c4514 # v5.4.2

jobs:
  ########
  # BUILD AND CACHE VTK
  update_vtk:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [x64, Win32]

    steps:        
    - name: Cache VTK Build
      id: cache-vtk
      uses: actions/cache@v4
      with:
        path: vtk-install
        lookup-only: true
        key: vtk-${{ runner.os }}-${{ matrix.arch }}-${{ env.VTK_HASH }}

    - name: Install Dependencies
      if: contains(matrix.os, 'ubuntu') && steps.cache-vtk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y cmake g++ libgl1-mesa-dev libxt-dev libxrender-dev libxext-dev libglu1-mesa-dev make

    - name: Install Qt
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v4
      with:
        dir: ${{github.workspace}}/Qt
        version: '5.15.0'
        arch: ${{ matrix.arch == 'x64' && 'win64_msvc2019_64' || 'win32_msvc2019' }}

    - name: Clone VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir vtk
        cd vtk
        git init
        git remote add origin https://gitlab.kitware.com/vtk/vtk.git
        git fetch --depth 1 origin $VTK_HASH
        git checkout FETCH_HEAD

    - name: Configure VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake -S vtk -B vtk-build -G "Visual Studio 17 2022" -A ${{ matrix.arch }} \
          -DCMAKE_INSTALL_PREFIX=vtk-install \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_SHARED_LIBS=ON \
          -DVTK_BUILD_TESTING=OFF \
          -DVTK_VERSIONED_INSTALL=OFF \
          -DVTK_GROUP_ENABLE_Qt:STRING=YES \
          -DQt5_DIR="${QT_DIR}"

    - name: Build VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake --build vtk-build --parallel 4 --config ${{ matrix.build_type }}

    - name: Install VTK
      if: steps.cache-vtk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake --install vtk-build

  update_itk:
    ########
    # BUILD AND CACHE ITK
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [x64, Win32]

    steps:
    - name: Cache ITK Build
      id: cache-itk
      uses: actions/cache@v4
      with:
        lookup-only: true
        path: itk-install
        key: itk-${{ runner.os }}-${{ matrix.arch }}-${{ env.ITK_HASH }}
        
    - name: Install Dependencies
      if: contains(matrix.os, 'ubuntu') && steps.cache-itk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y cmake g++ libgl1-mesa-dev libxt-dev libxrender-dev libxext-dev libglu1-mesa-dev make

    - name: Clone ITK
      if: steps.cache-itk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cloning ITK..."
        mkdir itk
        cd itk
        git init
        git remote add origin https://github.com/InsightSoftwareConsortium/ITK.git
        git fetch --depth 1 origin $ITK_HASH
        git checkout FETCH_HEAD

    - name: Configure ITK
      if: steps.cache-itk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake -S itk -B itk-build -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_INSTALL_PREFIX=itk-install -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF

    - name: Build ITK
      if: steps.cache-itk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake --build itk-build --parallel 4 --config ${{ matrix.build_type }}

    - name: Install ITK
      if: steps.cache-itk.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake --install itk-build

  build_plus_x64:
    needs: [update_vtk, update_itk]
    uses: ./.github/workflows/build-plus.yml
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [x64]
    secrets:
      pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
    with:
      arch: x64
      vtk-cache-key: vtk-Windows-x64-6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # todo: fix
      itk-cache-key: itk-Windows-x64-898def645183e6a2d3293058ade451ec416c4514
      plus-cache-key: plus-latest-x64
      archive-name: PlusApp-Win64
      plus-config: >-
        -DPLUS_USE_3dConnexion_TRACKER:BOOL=ON
        -DPLUS_USE_Ascension3DGm:BOOL=OFF
        -DPLUS_USE_BKPROFOCUS_VIDEO:BOOL=OFF
        -DPLUS_USE_EPIPHAN:BOOL=ON
        -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=OFF
        -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=ON
        -DPLUS_USE_NDI:BOOL=ON
        -DPLUS_USE_VFW_VIDEO:BOOL=ON
        -DPLUS_USE_OPTITRACK:BOOL=ON
        -DPLUS_USE_INTELREALSENSE:BOOL=ON
        -DPLUSBUILD_PREFER_MicronTracker_36:BOOL=OFF
        -DPLUS_USE_TextRecognizer:BOOL=ON
        -DPLUS_USE_WITMOTIONTRACKER:BOOL=ON
        -DPLUS_USE_MKV_IO:BOOL=ON
        -DPLUS_ENABLE_VIDEOSTREAMING:BOOL=ON
        -DPLUS_USE_VP9:BOOL=ON
        -DPLUSBUILD_BUILDNAME_POSTFIX=gh-package-x64
        -DPLUS_USE_Ascension3DG:BOOL=OFF
        -DPLUS_USE_BRACHY_TRACKER:BOOL=OFF
        -DPLUS_USE_NDI_CERTUS:BOOL=OFF
        -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF
        -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF
        -DPLUS_USE_MICRONTRACKER:BOOL=OFF
        -DPLUS_USE_MMF_VIDEO:BOOL=ON
        -DPLUS_USE_STEALTHLINK:BOOL=OFF
        -DPLUS_USE_OPTICAL_MARKER_TRACKER:BOOL=ON
        -DPLUSBUILD_USE_OpenCV:BOOL=ON
        -DPLUS_USE_OpenCV_VIDEO:BOOL=ON
        -DPLUSBUILD_USE_aruco:BOOL=ON

  build_plus_x64_clarius_cast:
    needs: [build_plus_x64] # Build off of the base x64 package
    uses: ./.github/workflows/build-plus.yml
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [x64]
    secrets:
      pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
    with:
      arch: x64
      vtk-cache-key: vtk-Windows-x64-6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # todo: fix
      itk-cache-key: itk-Windows-x64-898def645183e6a2d3293058ade451ec416c4514
      plus-cache-key: plus-latest-x64
      archive-name: PlusApp-Clarius-Win64
      plus-config: >-
        -DPLUSAPP_PACKAGE_EDITION:STRING="ClariusCast"
        -DPLUS_USE_CLARIUS:BOOL=ON

  build_plus_x64_clarius_oem:
      needs: [build_plus_x64] # Build off of the base x64 package
      uses: ./.github/workflows/build-plus.yml
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest]
          build_type: [Release]
          arch: [x64]
      secrets:
        pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
      with:
        arch: x64
        vtk-cache-key: vtk-Windows-x64-6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # todo: fix
        itk-cache-key: itk-Windows-x64-898def645183e6a2d3293058ade451ec416c4514
        plus-cache-key: plus-latest-x64
        archive-name: PlusApp-ClariusOEM-Win64
        plus-config: >-
          -DPLUSAPP_PACKAGE_EDITION:STRING="ClariusOEM"
          -DPLUS_USE_CLARIUS_OEM:BOOL=ON

  build_plus_x64_telemed:
    needs: [build_plus_x64] # Build off of the base x64 package
    uses: ./.github/workflows/build-plus.yml
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [x64]
    secrets:
      pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
    with:
      arch: x64
      vtk-cache-key: vtk-Windows-x64-6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # todo: fix
      itk-cache-key: itk-Windows-x64-898def645183e6a2d3293058ade451ec416c4514
      plus-cache-key: plus-latest-x64
      archive-name: PlusApp-Telemed-Win64
      plus-config: >-
        -DPLUSAPP_PACKAGE_EDITION:STRING="Telemed"
        -DPLUS_USE_TELEMED_VIDEO:BOOL=ON

  build_plus_Win32:
    needs: [update_vtk, update_itk]
    uses: ./.github/workflows/build-plus.yml
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        arch: [Win32]
    secrets:
      pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
    with:
      arch: Win32
      vtk-cache-key: vtk-Windows-Win32-6b6b89ee577e6c6a5ee6f5220b9c6a12513c30b4 # todo: fix
      itk-cache-key: itk-Windows-Win32-898def645183e6a2d3293058ade451ec416c4514
      plus-cache-key: plus-latest-Win32
      archive-name: PlusApp-Win32
      plus-config: >-
        -DPLUSBUILD_BUILDNAME_POSTFIX=gh-package-Win32
        -DPLUSBUILD_DOCUMENTATION:BOOL=OFF
        -DPLUS_USE_3dConnexion_TRACKER:BOOL=ON
        -DPLUS_USE_Ascension3DGm:BOOL=OFF
        -DPLUS_USE_BKPROFOCUS_VIDEO:BOOL=OFF
        -DPLUS_USE_EPIPHAN:BOOL=ON
        -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=ON
        -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=ON
        -DPLUS_USE_NDI:BOOL=ON
        -DPLUS_USE_VFW_VIDEO:BOOL=ON
        -DPLUS_USE_OPTITRACK:BOOL=ON
        -DPLUS_USE_INTELREALSENSE:BOOL=ON
        -DPLUSBUILD_PREFER_MicronTracker_36:BOOL=OFF
        -DPLUS_USE_TextRecognizer:BOOL=ON
        -DPLUS_USE_WITMOTIONTRACKER:BOOL=ON 
        -DPLUS_USE_MKV_IO:BOOL=ON
        -DPLUS_ENABLE_VIDEOSTREAMING:BOOL=ON
        -DPLUS_USE_VP9:BOOL=ON
        -DPLUS_USE_Ascension3DG:BOOL=ON
        -DPLUS_USE_BRACHY_TRACKER:BOOL=ON
        -DPLUS_USE_NDI_CERTUS:BOOL=ON
        -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF
        -DPLUS_ULTRASONIX_SDK_MAJOR_VERSION:STRING=6
        -DPLUS_ULTRASONIX_SDK_MINOR_VERSION:STRING=1
        -DPLUS_ULTRASONIX_SDK_PATCH_VERSION:STRING=1
