name: Continuous integration
'on':
  workflow_dispatch: null
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  update_vtk_Win32:
    uses: ./.github/workflows/build-vtk.yml
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        build_type:
        - Release
        arch:
        - Win32
    with:
      vtk-hash: f49a1dbafa60b58ef22f6292ec58370453162192
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build-type: ${{ matrix.build_type }}
  update_itk_Win32:
    uses: ./.github/workflows/build-itk.yml
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        build_type:
        - Release
        arch:
        - Win32
    with:
      itk-hash: f7ff6ad56d487d9f52e6ba1dbbd9a816a14b5158
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build-type: ${{ matrix.build_type }}
  build_plus_Win32:
    needs:
    - update_vtk_Win32
    - update_itk_Win32
    uses: ./.github/workflows/build-plus.yml
    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        build_type:
        - Release
        arch:
        - Win32
    secrets:
      pltools-access-token: ${{ secrets.PLTOOLS_ACCESS_TOKEN }}
    with:
      arch: ${{ matrix.arch }}
      os: ${{ matrix.os }}
      pluslib-repository: https://github.com/${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}.git
      pluslib-tag: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      vtk-cache-key: ${{ needs.update_vtk_Win32.outputs.cache-key }}
      itk-cache-key: ${{ needs.update_itk_Win32.outputs.cache-key }}
      run-tests: true
      archive-name: PlusApp-Win32
      plus-config: -DVTK_DIR=${{ needs.update_vtk_Win32.outputs.install-path }} -DITK_DIR=${{ needs.update_itk_Win32.outputs.install-path }} -DPLUSAPP_PACKAGE_EDITION:STRING="" -DPLUSBUILD_BUILDNAME_POSTFIX=gh-ci-Win32 -DPLUSBUILD_DOCUMENTATION:BOOL=OFF -DPLUS_USE_3dConnexion_TRACKER:BOOL=ON -DPLUS_USE_EPIPHAN:BOOL=ON -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=ON -DPLUS_USE_NDI:BOOL=ON -DPLUS_USE_VFW_VIDEO:BOOL=ON -DPLUS_USE_TextRecognizer:BOOL=ON -DPLUS_USE_WITMOTIONTRACKER:BOOL=ON -DPLUS_USE_MKV_IO:BOOL=ON -DPLUS_ENABLE_VIDEOSTREAMING:BOOL=ON -DPLUS_USE_VP9:BOOL=ON -DPLUS_USE_Ascension3DG:BOOL=ON -DPLUS_USE_BRACHY_TRACKER:BOOL=ON -DPLUS_USE_MMF_VIDEO:BOOL=ON -DPLUS_USE_OPTICAL_MARKER_TRACKER:BOOL=ON -DPLUSBUILD_USE_OpenCV:BOOL=ON -DPLUSBUILD_USE_aruco:BOOL=ON -DPLUS_USE_OpenCV_VIDEO:BOOL=ON
      ctest-extra-args: -R CenterOfRotationCalibration-Ulterius
      plus-cache-key: plus-debug-Win32
